// i18n dictionary + LangCtx React context.
// Top-level `var` bindings attach to the global scope across split Babel tags.

var DICT = {
  en: {
    brand_sub: "",
    index_status: "ready",
    toggle_theme: "Toggle theme",
    settings: "Settings",
    lang_label: "EN",
    lang_other: "ZH",
    language_switch_tip: "Switch language",

    search_placeholder: "Search your documents...",
    mode_keyword: "Keyword",
    mode_hybrid: "Hybrid",
    mode_semantic: "Semantic",
    btn_search: "Search",
    search_loading: "Searching...",
    search_failed: "Search failed",
    search_empty_title: "Search your documents",
    search_empty_hint: "Drop PDF, DOCX, XLSX, or PPTX files into the watched_docs folder, then type a query above",
    coming_soon: "Coming soon",
    coming_soon_short: "(soon)",
    view_documents: "Documents",
    view_occurrences: "All matches",
    view_tip: "Documents = ranked chunks. All matches = every Ctrl+F-style occurrence.",
    whole_word: "Whole word",
    whole_word_tip: "Match the whole word only (e.g. 'bios' won't match 'biosphere').",
    match_case: "Match case",
    match_case_tip: "Match uppercase and lowercase exactly.",
    advanced: "Advanced",
    related_terms: "Related terms",
    related_placeholder: "Add term...",
    matches_n: "matches",
    occurrences_in_chunk_tip: "Number of times the query appears in this chunk.",
    match_at: "match @",
    load_more: "Load more",
    loading_more: "Loading...",

    f_vendor: "Document",
    f_explorer: "Found Files",
    f_spec_type: "File Type",
    f_category: "Category",
    f_score_range: "Score Range",
    f_date: "Date",
    f_clear: "clear",

    results_n: "results",
    results_ms: "ms",
    sort: "SORT",
    sort_relevance: "Relevance",
    sort_name: "Name (A-Z)",
    sort_date: "Date (newest)",
    layout_detailed: "Detailed",
    layout_compact: "Compact",

    empty_msg: "Select a result to preview",
    open: "open",
    meta_doc: "Document",
    meta_version: "Version",
    meta_page: "Page",
    meta_published: "Published",
    score_fused: "FUSED",
    score_fused_tip: "FUSED is the final hybrid ranking score after combining keyword BM25 and semantic cosine signals.",
    score_bm25_tip: "BM25 is keyword relevance from full-text search. Higher means the query terms match the text more strongly.",
    score_cos_tip: "cos is cosine similarity from embeddings. Higher means the meaning of the chunk is closer to the query.",
    tab_context: "Context",
    tab_match: "Matched chunk",
    tab_metadata: "Metadata",
    tab_related: "Related",
    tab_doc_chunks: "Document chunks",
    ctx_preceding: "Preceding context",
    ctx_matched: "Matched chunk",
    ctx_following: "Following context",
    matched_only: "Matched chunk only",
    other_chunks: "Other chunks from",
    copy_citation: "copy citation",
    copy_text: "copy text",
    download_pdf: "Download document",
    page_short: "p.",

    docs_nav: "Library",
    docs_back: "Back to search",
    docs_list: "View as list",
    docs_explorer: "View as tree",
    docs_empty: "No documents indexed yet",
    docs_empty_hint: "Drop PDF, DOCX, XLSX, or PPTX files into the watched folder to start indexing.",
    docs_search: "Filter files...",
    docs_chunks: "chunks",
    docs_tags: "Tags",
    docs_tags_folder: "Folders",
    docs_tags_custom: "Custom",
    docs_new_tag: "New tag name...",
    docs_add: "Add",
    docs_tag_assign: "Assign tags",
    docs_open: "Open",
    docs_all_files: "All files",
    docs_refresh: "Scan for new files",
    docs_tag_mode: "Tag mode",
    docs_auto_tags: "By subfolder",
    docs_manual_tags: "Individual",
    docs_apply_folder_tags: "Apply folder tags",
    docs_remove_all_tags: "Remove all tags",
    docs_add_tag: "Add Tag",
    docs_edit_tag: "Edit Tag",
    docs_remove_tag: "Remove tag",
    docs_no_tags: "No tags yet",
    docs_tags_assigned: "Assigned",
    docs_tags_available: "Available",
    docs_index_updating: "Updating index",
    docs_indexing: "indexing",
    docs_delete_tag_confirm: 'Delete tag "{name}"?',
    docs_apply_folder_tags_confirm: "Apply folder tags to all files?",
    docs_folder_tags_applied: "Applied {changedDocs} files, created {created} tags",
    docs_remove_all_tags_confirm: "Remove all tags and all file assignments?",
    docs_all_tags_removed: "Removed all tags",
    docs_files_count: "files",
    docs_color: "Color",
    docs_new_tag_short: "New tag...",
    docs_tag_name_placeholder: "Tag name...",

    confirm_cancel: "Cancel",
    confirm_ok: "Confirm",
    confirm_danger: "Delete",

    bookmarks_title: "Bookmarks",
    bookmarks_nav: "Bookmarks",
    bookmarks_back: "Back to search",
    bookmarks_empty: "No bookmarks yet",
    bookmarks_empty_hint: "Star a result in the preview panel to save it here for quick access later.",
    bookmarks_count: "saved",
    bookmarks_remove: "Remove",
    bookmarks_open: "open",
    bookmarks_clear_all: "Clear all",
    bookmarks_clear_confirm: "Clear all {count} bookmarks?",
    bookmarks_filter: "Filter bookmarks...",
    bookmarks_count_label: "bookmarks",
    bookmarks_no_matches: "No matches",
    bookmarks_no_matches_hint: "Try a different filter",
    bookmark_add: "Bookmark",
    bookmark_added: "Bookmarked",

    sb_connected: "connected - localhost:8000",
    sb_mode: "mode:",
    sb_embedder: "embedder: bge-small-en-v1.5 - 384d",
    sb_alpha: "RRF fusion (BM25 + cosine)",
    sb_cache: "fastembed - ONNX",
    sb_chunks: "chunks",
    sb_docs: "docs",
    sb_matches: "matches",

    tw_layout: "Layout",
    tw_language: "Language",
    tw_interface_language: "Interface language",
    tw_zh: "Chinese",
    tw_appearance: "Appearance",
    tw_theme: "Theme",
    tw_light: "Light",
    tw_dark: "Dark",
    tw_filters_pos: "Filters position",
    tw_sidebar: "Sidebar",
    tw_topbar: "Top bar",
    tw_result_card: "Result card",
    tw_density: "Density",
    tw_density_compact: "Compact",
    tw_density_balanced: "Balanced",
    tw_density_spacious: "Spacious",
    tw_theming: "Theming",
    tw_accent: "Accent color",
    tw_typography: "Typography",
    tw_body_font: "Body font (Sans)",
    tw_mono_font: "Monospace font",
    tw_display_font: "Heading font (Display)",
    tw_system_font: "System",
    tw_highlight: "Highlight style",
    tw_yellow: "Yellow",
    tw_underline: "Underline",
    tw_bold: "Bold",
    tw_indigo: "Indigo (default)",
    tw_emerald: "Emerald",
    tw_amber: "Amber",
    tw_slate: "Slate",
  },
  zh: {
    brand_sub: "",
    index_status: "就緒",
    toggle_theme: "切換主題",
    settings: "設定",
    lang_label: "中",
    lang_other: "EN",
    language_switch_tip: "切換語言",

    search_placeholder: "搜尋你的文件...",
    mode_keyword: "關鍵字",
    mode_hybrid: "混合",
    mode_semantic: "語意",
    btn_search: "搜尋",
    search_loading: "搜尋中...",
    search_failed: "搜尋失敗",
    search_empty_title: "搜尋你的文件",
    search_empty_hint: "將 PDF、DOCX、XLSX 或 PPTX 放入 watched_docs 資料夾，然後輸入查詢。",
    coming_soon: "即將推出",
    coming_soon_short: "(即將)",
    view_documents: "文件",
    view_occurrences: "全部符合",
    view_tip: "文件 = 依相關性排序的區塊。全部符合 = 類似 Ctrl+F 的每個出現位置。",
    whole_word: "整字匹配",
    whole_word_tip: "只匹配完整單字，例如 bios 不會匹配 biosphere。",
    match_case: "大小寫匹配",
    match_case_tip: "精確匹配大小寫。",
    advanced: "進階",
    related_terms: "相關詞",
    related_placeholder: "新增詞...",
    matches_n: "符合",
    occurrences_in_chunk_tip: "查詢字串在此區塊中出現的次數。",
    match_at: "位置 @",
    load_more: "載入更多",
    loading_more: "載入中...",

    f_vendor: "文件",
    f_explorer: "找到的檔案",
    f_spec_type: "檔案類型",
    f_category: "分類",
    f_score_range: "分數範圍",
    f_date: "日期",
    f_clear: "清除",

    results_n: "筆結果",
    results_ms: "毫秒",
    sort: "排序",
    sort_relevance: "相關性",
    sort_name: "名稱 (A-Z)",
    sort_date: "日期 (最新)",
    layout_detailed: "詳細",
    layout_compact: "精簡",

    empty_msg: "選擇一筆結果以預覽",
    open: "開啟",
    meta_doc: "文件",
    meta_version: "版本",
    meta_page: "頁",
    meta_published: "發布",
    score_fused: "融合",
    score_fused_tip: "融合分數是結合 BM25 關鍵字分數與語意 cosine 分數後的最終排名。",
    score_bm25_tip: "BM25 是全文搜尋的關鍵字相關性。越高代表查詢詞越符合文字。",
    score_cos_tip: "cos 是嵌入向量 cosine 相似度。越高代表語意越接近查詢。",
    tab_context: "上下文",
    tab_match: "符合區塊",
    tab_metadata: "中繼資料",
    tab_related: "相關",
    tab_doc_chunks: "文件區塊",
    ctx_preceding: "前文",
    ctx_matched: "符合區塊",
    ctx_following: "後文",
    matched_only: "僅符合區塊",
    other_chunks: "同文件其他區塊",
    copy_citation: "複製引用",
    copy_text: "複製文字",
    download_pdf: "下載文件",
    page_short: "頁",

    docs_nav: "知識庫",
    docs_back: "返回搜尋",
    docs_list: "清單檢視",
    docs_explorer: "樹狀檢視",
    docs_empty: "尚未建立索引",
    docs_empty_hint: "將文件放入 watched_docs 資料夾以開始索引。",
    docs_search: "篩選檔案...",
    docs_chunks: "區塊",
    docs_tags: "標籤",
    docs_tags_folder: "資料夾",
    docs_tags_custom: "自訂",
    docs_new_tag: "新標籤名稱...",
    docs_add: "新增",
    docs_tag_assign: "指派標籤",
    docs_open: "開啟",
    docs_all_files: "全部檔案",
    docs_refresh: "掃描新檔案",
    docs_tag_mode: "標籤模式",
    docs_auto_tags: "依子資料夾",
    docs_manual_tags: "個別",
    docs_apply_folder_tags: "套用資料夾標籤",
    docs_remove_all_tags: "移除全部標籤",
    docs_add_tag: "新增標籤",
    docs_edit_tag: "編輯標籤",
    docs_remove_tag: "移除標籤",
    docs_no_tags: "尚無標籤",
    docs_tags_assigned: "已指派",
    docs_tags_available: "可用",
    docs_index_updating: "索引更新中",
    docs_indexing: "索引中",
    docs_delete_tag_confirm: "刪除標籤「{name}」？",
    docs_apply_folder_tags_confirm: "將資料夾標籤套用到所有檔案？",
    docs_folder_tags_applied: "已套用 {changedDocs} 個檔案，建立 {created} 個標籤",
    docs_remove_all_tags_confirm: "移除所有標籤與檔案指派？",
    docs_all_tags_removed: "已移除全部標籤",
    docs_files_count: "個檔案",
    docs_color: "顏色",
    docs_new_tag_short: "新標籤...",
    docs_tag_name_placeholder: "標籤名稱...",

    confirm_cancel: "取消",
    confirm_ok: "確認",
    confirm_danger: "刪除",

    bookmarks_title: "收藏",
    bookmarks_nav: "收藏",
    bookmarks_back: "返回搜尋",
    bookmarks_empty: "尚無收藏",
    bookmarks_empty_hint: "在預覽面板收藏結果，之後即可快速查閱。",
    bookmarks_count: "已儲存",
    bookmarks_remove: "移除",
    bookmarks_open: "開啟",
    bookmarks_clear_all: "全部清空",
    bookmarks_clear_confirm: "清空全部 {count} 筆收藏？",
    bookmarks_filter: "篩選收藏...",
    bookmarks_count_label: "筆收藏",
    bookmarks_no_matches: "無符合結果",
    bookmarks_no_matches_hint: "請嘗試不同篩選",
    bookmark_add: "加入收藏",
    bookmark_added: "已收藏",

    sb_connected: "已連線 - localhost:8000",
    sb_mode: "模式：",
    sb_embedder: "嵌入模型：bge-small-en-v1.5 - 384d",
    sb_alpha: "RRF 融合 (BM25 + cosine)",
    sb_cache: "fastembed - ONNX",
    sb_chunks: "區塊",
    sb_docs: "文件",
    sb_matches: "符合",

    tw_layout: "版面",
    tw_language: "語言",
    tw_interface_language: "介面語言",
    tw_zh: "中文",
    tw_appearance: "外觀",
    tw_theme: "主題",
    tw_light: "淺色",
    tw_dark: "深色",
    tw_filters_pos: "篩選位置",
    tw_sidebar: "側邊欄",
    tw_topbar: "頂部列",
    tw_result_card: "結果卡片",
    tw_density: "密度",
    tw_density_compact: "精簡",
    tw_density_balanced: "平衡",
    tw_density_spacious: "寬鬆",
    tw_theming: "主題設定",
    tw_accent: "強調色",
    tw_typography: "字體",
    tw_body_font: "內文字體",
    tw_mono_font: "等寬字體",
    tw_display_font: "標題字體",
    tw_system_font: "系統",
    tw_highlight: "標示樣式",
    tw_yellow: "黃色",
    tw_underline: "底線",
    tw_bold: "粗體",
    tw_indigo: "靛藍 (預設)",
    tw_emerald: "翡翠",
    tw_amber: "琥珀",
    tw_slate: "石板",
  },
};

var LANG_META = {
  en: { htmlLang: "en", locale: "en-US", next: "zh" },
  zh: { htmlLang: "zh-TW", locale: "zh-TW", next: "en" },
};

function getLangMeta(lang) {
  return LANG_META[lang] || LANG_META.en;
}

function getHtmlLang(lang) {
  return getLangMeta(lang).htmlLang;
}

function getLocale(lang) {
  return getLangMeta(lang).locale;
}

function getNextLang(lang) {
  return getLangMeta(lang).next;
}

function translate(lang, key, vars) {
  const text = DICT[lang]?.[key] ?? DICT.en?.[key] ?? key;
  if (!vars) return text;
  return String(text).replace(/\{(\w+)\}/g, (_, name) => vars[name] ?? "");
}

var LangCtx = React.createContext("en");
function useT() {
  const lang = React.useContext(LangCtx);
  return React.useCallback((key, vars) => translate(lang, key, vars), [lang]);
}
