// i18n dictionary + LangCtx React context.
// Top-level `var` (not `const`) so DICT, LangCtx, useT attach to the global
// scope across split <script type="text/babel"> tags.

var DICT = {
  en: {
    brand_sub: "",
    index_status: "ready",
    toggle_theme: "Toggle theme",
    lang_label: "EN",
    lang_other: "繁",

    // search row
    search_placeholder: 'Search your documents...',
    mode_keyword: "Keyword",
    mode_hybrid: "Hybrid",
    mode_semantic: "Semantic",
    btn_search: "Search",

    // filters
    f_vendor: "Document",
    f_spec_type: "File Type",
    f_category: "Category",
    f_score_range: "Score Range",
    f_date: "Date",
    f_clear: "clear",

    // results
    results_n: "results",
    results_ms: "ms",
    sort: "SORT",
    sort_relevance: "Relevance",
    sort_name: "Name (A-Z)",
    sort_date: "Date (newest)",
    layout_detailed: "Detailed",
    layout_compact: "Compact",

    // preview
    empty_msg: "Select a result to preview",
    open: "open",
    meta_doc: "Document",
    meta_version: "Version",
    meta_page: "Page",
    meta_published: "Published",
    score_fused: "FUSED",
    score_fused_tip: "FUSED is the final hybrid ranking score after combining keyword BM25 and semantic cosine signals.",
    score_bm25_tip: "BM25 is keyword relevance from full-text search. Higher means the query terms match the text more strongly.",
    score_cos_tip: "cos is cosine similarity from embeddings. Higher means the meaning of the chunk is closer to the query.",
    tab_context: "Context",
    tab_match: "Matched chunk",
    tab_metadata: "Metadata",
    tab_related: "Related",
    ctx_preceding: "Preceding context",
    ctx_matched: "★ Matched chunk",
    ctx_following: "Following context",
    matched_only: "Matched chunk only",
    other_chunks: "Other chunks from",
    copy_citation: "copy citation",
    copy_text: "copy text",
    download_pdf: "Download document",
    page_short: "p.",

    // documents view
    docs_nav:        "Files",
    docs_back:       "Back to search",
    docs_list:       "List view",
    docs_explorer:   "Explorer view",
    docs_empty:      "No documents indexed yet",
    docs_empty_hint: "Drop PDF, DOCX, XLSX, or PPTX files into the watched folder to start indexing.",
    docs_search:     "Filter files...",
    docs_chunks:     "chunks",
    docs_tags:       "Tags",
    docs_tags_folder: "Folders",
    docs_tags_custom: "Custom",
    docs_new_tag:    "New tag name...",
    docs_add:        "Add",
    docs_tag_assign: "Assign tags",
    docs_open:       "Open",
    docs_all_files:  "All files",

    // bookmarks page
    bookmarks_title:    "Bookmarks",
    bookmarks_nav:      "Bookmarks",
    bookmarks_back:     "Back to search",
    bookmarks_empty:    "No bookmarks yet",
    bookmarks_empty_hint: "Star a result in the preview panel to save it here for quick access later.",
    bookmarks_count:    "saved",
    bookmarks_remove:   "Remove",
    bookmarks_open:     "open",
    bookmarks_clear_all: "Clear all",

    // statusbar
    sb_connected: "connected · localhost:8000",
    sb_mode: "mode:",
    sb_embedder: "embedder: bge-small-en-v1.5 · 384d",
    sb_alpha: "RRF fusion (BM25 + cosine)",
    sb_cache: "fastembed · ONNX",
    sb_chunks: "chunks",

    // tweaks
    tw_layout: "Layout",
    tw_filters_pos: "Filters position",
    tw_sidebar: "Sidebar",
    tw_topbar: "Top bar",
    tw_result_card: "Result card",
    tw_density: "Density",
    tw_density_compact: "Compact",
    tw_density_balanced: "Balanced",
    tw_density_spacious: "Spacious",
    tw_theming: "Theming",
    tw_accent: "Accent color",
    tw_typography: "Typography",
    tw_highlight: "Highlight style",
    tw_yellow: "Yellow",
    tw_underline: "Underline",
    tw_bold: "Bold",
    tw_indigo: "Indigo (default)",
    tw_emerald: "Emerald",
    tw_amber: "Amber",
    tw_slate: "Slate",
  },
  zh: {
    brand_sub: "",
    index_status: "就緒",
    toggle_theme: "切換主題",
    lang_label: "繁",
    lang_other: "EN",

    search_placeholder: '搜尋你的文件...',
    mode_keyword: "關鍵字",
    mode_hybrid: "混合",
    mode_semantic: "語意",
    btn_search: "搜尋",

    f_vendor: "文件",
    f_spec_type: "檔案類型",
    f_category: "分類",
    f_score_range: "分數範圍",
    f_date: "日期",
    f_clear: "清除",

    results_n: "筆結果",
    results_ms: "毫秒",
    sort: "排序",
    sort_relevance: "相關度",
    sort_name: "名稱 (A-Z)",
    sort_date: "日期 (最新)",
    layout_detailed: "詳細",
    layout_compact: "精簡",

    empty_msg: "請選擇一筆結果以預覽",
    open: "開啟",
    meta_doc: "文件",
    meta_version: "版本",
    meta_page: "頁碼",
    meta_published: "發布日期",
    score_fused: "融合",
    score_fused_tip: "融合分數是混合搜尋的最終排序分數，結合 BM25 關鍵字與 cos 語意相似度。",
    score_bm25_tip: "BM25 是全文搜尋的關鍵字相關度。分數越高，代表查詢詞與文字越匹配。",
    score_cos_tip: "cos 是向量嵌入的餘弦相似度。分數越高，代表內容語意越接近查詢。",
    tab_context: "上下文",
    tab_match: "命中區塊",
    tab_metadata: "中繼資料",
    tab_related: "相關",
    ctx_preceding: "前文",
    ctx_matched: "★ 命中區塊",
    ctx_following: "後文",
    matched_only: "僅顯示命中區塊",
    other_chunks: "來自此規格的其他區塊：",
    copy_citation: "複製引用",
    copy_text: "複製內文",
    download_pdf: "下載文件",
    page_short: "第",

    docs_nav:        "檔案",
    docs_back:       "返回搜尋",
    docs_list:       "清單檢視",
    docs_explorer:   "樹狀檢視",
    docs_empty:      "尚未索引任何文件",
    docs_empty_hint: "將 PDF、DOCX、XLSX 或 PPTX 拖入監看資料夾,系統會自動開始索引。",
    docs_search:     "過濾檔案...",
    docs_chunks:     "區塊",
    docs_tags:       "標籤",
    docs_tags_folder: "資料夾",
    docs_tags_custom: "自訂",
    docs_new_tag:    "輸入新標籤名稱...",
    docs_add:        "新增",
    docs_tag_assign: "指派標籤",
    docs_open:       "開啟",
    docs_all_files:  "全部檔案",

    bookmarks_title:    "我的收藏",
    bookmarks_nav:      "收藏",
    bookmarks_back:     "返回搜尋",
    bookmarks_empty:    "尚未收藏任何項目",
    bookmarks_empty_hint: "在預覽面板點擊星號,即可將結果加入收藏方便日後查閱。",
    bookmarks_count:    "筆收藏",
    bookmarks_remove:   "移除",
    bookmarks_open:     "開啟",
    bookmarks_clear_all: "全部清空",

    sb_connected: "已連線 · localhost:8000",
    sb_mode: "模式：",
    sb_embedder: "嵌入模型：bge-small-en-v1.5 · 384 維",
    sb_alpha: "RRF 融合 (BM25 + 餘弦)",
    sb_cache: "fastembed · ONNX",
    sb_chunks: "區塊",

    tw_layout: "版面",
    tw_filters_pos: "篩選器位置",
    tw_sidebar: "側邊欄",
    tw_topbar: "頂部列",
    tw_result_card: "結果卡片",
    tw_density: "密度",
    tw_density_compact: "精簡",
    tw_density_balanced: "平衡",
    tw_density_spacious: "寬鬆",
    tw_theming: "主題樣式",
    tw_accent: "強調色",
    tw_typography: "字體",
    tw_highlight: "標示樣式",
    tw_yellow: "黃底",
    tw_underline: "底線",
    tw_bold: "粗體",
    tw_indigo: "靛藍 (預設)",
    tw_emerald: "翠綠",
    tw_amber: "琥珀",
    tw_slate: "石板",
  }
};

var LangCtx = React.createContext('en');
function useT() {
  const lang = React.useContext(LangCtx);
  return (key) => DICT[lang]?.[key] ?? DICT['en']?.[key] ?? key;
}
